# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[
        ('tesseract-ocr/tesseract.exe', 'tesseract-ocr'),
        ('tesseract-ocr/*.dll', 'tesseract-ocr'),
    ],
    datas=[
        ('app/build', 'app/build'),
        ('modules', 'modules'),
        ('configs', 'configs'),
        ('tesseract-ocr', 'tesseract-ocr'),
        ('version.json', '.'),
        ('*.json', '.'),  # Include all JSON config files
    ],
    hiddenimports=[
        'keyboard', 
        'pkg_resources.extern', 
        'webview',
        'webview.platforms.winforms',
        'webview.platforms.cef',
        'webview.platforms.qt',
        'webview.platforms.edgechromium',
        'webview.util',
        'webview.menu',
        'webview.js',
        'pythonnet',
        'clr',
        'flask',
        'modules.routes',
        'modules.events',
        'modules.utils',
        'modules.key_mapper',
        'modules.snipper',
        'modules.updater',
        'requests',
        'packaging.version',
        'pyautogui',
        'pytesseract',
        'PIL',
        'PIL.ImageGrab',
        'cv2',
        'opencv-python',
        'easyocr',
        'numpy',
        'PyQt5',
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'winsound',
        'datetime',
        'threading',
        'json',
        'os',
        'sys',
        'io',
        'tempfile',
        'shutil',
        'subprocess',
        'zipfile',
        'typing',
        'sip',
        'PyQt5.sip',
        'encodings',
        'encodings.utf_8',
        'encodings.cp1252',
        'win32api',
        'win32gui',
        'win32con',
        'pywintypes',
    ],
    hookspath=['.'],
    runtime_hooks=['runtime_hook.py'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='pokemacro',
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    debug=False,
    console=False,  # Set to True for debugging if needed
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='pokemacro'
)
