export const KeyboardKeys = {
  Escape: { keyName: "Escape", keyNumber: 0 },
  F1: { keyName: "F1", keyNumber: 1 },
  F2: { keyName: "F2", keyNumber: 2 },
  F3: { keyName: "F3", keyNumber: 3 },
  F4: { keyName: "F4", keyNumber: 4 },
  F5: { keyName: "F5", keyNumber: 5 },
  F6: { keyName: "F6", keyNumber: 6 },
  F7: { keyName: "F7", keyNumber: 7 },
  F8: { keyName: "F8", keyNumber: 8 },
  F9: { keyName: "F9", keyNumber: 9 },
  F10: { keyName: "F10", keyNumber: 10 },
  F11: { keyName: "F11", keyNumber: 11 },
  F12: { keyName: "F12", keyNumber: 12 },
  F13: { keyName: "F13", keyNumber: 13 },
  F14: { keyName: "F14", keyNumber: 14 },
  F15: { keyName: "F15", keyNumber: 15 },
  F16: { keyName: "F16", keyNumber: 16 },
  F17: { keyName: "F17", keyNumber: 17 },
  F18: { keyName: "F18", keyNumber: 18 },
  F19: { keyName: "F19", keyNumber: 19 },
  F20: { keyName: "F20", keyNumber: 20 },
  F21: { keyName: "F21", keyNumber: 21 },
  F22: { keyName: "F22", keyNumber: 22 },
  F23: { keyName: "F23", keyNumber: 23 },
  F24: { keyName: "F24", keyNumber: 24 },
  Print: { keyName: "Print", keyNumber: 25 },
  ScrollLock: { keyName: "ScrollLock", keyNumber: 26 },
  Pause: { keyName: "Pause", keyNumber: 27 },
  Grave: { keyName: "Grave", keyNumber: 28 },
  Num1: { keyName: "Num1", keyNumber: 29 },
  Num2: { keyName: "Num2", keyNumber: 30 },
  Num3: { keyName: "Num3", keyNumber: 31 },
  Num4: { keyName: "Num4", keyNumber: 32 },
  Num5: { keyName: "Num5", keyNumber: 33 },
  Num6: { keyName: "Num6", keyNumber: 34 },
  Num7: { keyName: "Num7", keyNumber: 35 },
  Num8: { keyName: "Num8", keyNumber: 36 },
  Num9: { keyName: "Num9", keyNumber: 37 },
  Num0: { keyName: "Num0", keyNumber: 38 },
  Minus: { keyName: "Minus", keyNumber: 39 },
  Equal: { keyName: "Equal", keyNumber: 40 },
  Backspace: { keyName: "Backspace", keyNumber: 41 },
  Insert: { keyName: "Insert", keyNumber: 42 },
  Home: { keyName: "Home", keyNumber: 43 },
  PageUp: { keyName: "PageUp", keyNumber: 44 },
  NumLock: { keyName: "NumLock", keyNumber: 45 },
  Divide: { keyName: "Divide", keyNumber: 46 },
  Multiply: { keyName: "Multiply", keyNumber: 47 },
  Subtract: { keyName: "Subtract", keyNumber: 48 },
  Tab: { keyName: "Tab", keyNumber: 49 },
  Q: { keyName: "Q", keyNumber: 50 },
  W: { keyName: "W", keyNumber: 51 },
  E: { keyName: "E", keyNumber: 52 },
  R: { keyName: "R", keyNumber: 53 },
  T: { keyName: "T", keyNumber: 54 },
  Y: { keyName: "Y", keyNumber: 55 },
  U: { keyName: "U", keyNumber: 56 },
  I: { keyName: "I", keyNumber: 57 },
  O: { keyName: "O", keyNumber: 58 },
  P: { keyName: "P", keyNumber: 59 },
  LeftBracket: { keyName: "LeftBracket", keyNumber: 60 },
  RightBracket: { keyName: "RightBracket", keyNumber: 61 },
  Backslash: { keyName: "Backslash", keyNumber: 62 },
  Delete: { keyName: "Delete", keyNumber: 63 },
  End: { keyName: "End", keyNumber: 64 },
  PageDown: { keyName: "PageDown", keyNumber: 65 },
  NumPad7: { keyName: "NumPad7", keyNumber: 66 },
  NumPad8: { keyName: "NumPad8", keyNumber: 67 },
  NumPad9: { keyName: "NumPad9", keyNumber: 68 },
  Add: { keyName: "Add", keyNumber: 69 },
  CapsLock: { keyName: "CapsLock", keyNumber: 70 },
  A: { keyName: "A", keyNumber: 71 },
  S: { keyName: "S", keyNumber: 72 },
  D: { keyName: "D", keyNumber: 73 },
  F: { keyName: "F", keyNumber: 74 },
  G: { keyName: "G", keyNumber: 75 },
  H: { keyName: "H", keyNumber: 76 },
  J: { keyName: "J", keyNumber: 77 },
  K: { keyName: "K", keyNumber: 78 },
  L: { keyName: "L", keyNumber: 79 },
  Semicolon: { keyName: "Semicolon", keyNumber: 80 },
  Quote: { keyName: "Quote", keyNumber: 81 },
  Return: { keyName: "Return", keyNumber: 82 },
  NumPad4: { keyName: "NumPad4", keyNumber: 83 },
  NumPad5: { keyName: "NumPad5", keyNumber: 84 },
  NumPad6: { keyName: "NumPad6", keyNumber: 85 },
  LeftShift: { keyName: "LeftShift", keyNumber: 86 },
  Z: { keyName: "Z", keyNumber: 87 },
  X: { keyName: "X", keyNumber: 88 },
  C: { keyName: "C", keyNumber: 89 },
  V: { keyName: "V", keyNumber: 90 },
  B: { keyName: "B", keyNumber: 91 },
  N: { keyName: "N", keyNumber: 92 },
  M: { keyName: "M", keyNumber: 93 },
  Comma: { keyName: "Comma", keyNumber: 94 },
  Period: { keyName: "Period", keyNumber: 95 },
  Slash: { keyName: "Slash", keyNumber: 96 },
  RightShift: { keyName: "RightShift", keyNumber: 97 },
  Up: { keyName: "Up", keyNumber: 98 },
  NumPad1: { keyName: "NumPad1", keyNumber: 99 },
  NumPad2: { keyName: "NumPad2", keyNumber: 100 },
  NumPad3: { keyName: "NumPad3", keyNumber: 101 },
  Enter: { keyName: "Enter", keyNumber: 102 },
  LeftControl: { keyName: "LeftControl", keyNumber: 103 },
  LeftSuper: { keyName: "LeftSuper", keyNumber: 104 },
  LeftWin: { keyName: "LeftWin", keyNumber: 105 },
  LeftCmd: { keyName: "LeftCmd", keyNumber: 106 },
  LeftAlt: { keyName: "LeftAlt", keyNumber: 107 },
  Space: { keyName: "Space", keyNumber: 108 },
  RightAlt: { keyName: "RightAlt", keyNumber: 109 },
  RightSuper: { keyName: "RightSuper", keyNumber: 110 },
  RightWin: { keyName: "RightWin", keyNumber: 111 },
  RightCmd: { keyName: "RightCmd", keyNumber: 112 },
  Menu: { keyName: "Menu", keyNumber: 113 },
  RightControl: { keyName: "RightControl", keyNumber: 114 },
  Fn: { keyName: "Fn", keyNumber: 115 },
  Left: { keyName: "Left", keyNumber: 116 },
  Down: { keyName: "Down", keyNumber: 117 },
  Right: { keyName: "Right", keyNumber: 118 },
  NumPad0: { keyName: "NumPad0", keyNumber: 119 },
  Decimal: { keyName: "Decimal", keyNumber: 120 },
  Clear: { keyName: "Clear", keyNumber: 121 },
  AudioMute: { keyName: "AudioMute", keyNumber: 122 },
  AudioVolDown: { keyName: "AudioVolDown", keyNumber: 123 },
  AudioVolUp: { keyName: "AudioVolUp", keyNumber: 124 },
  AudioPlay: { keyName: "AudioPlay", keyNumber: 125 },
  AudioStop: { keyName: "AudioStop", keyNumber: 126 },
  AudioPause: { keyName: "AudioPause", keyNumber: 127 },
  AudioPrev: { keyName: "AudioPrev", keyNumber: 128 },
  AudioNext: { keyName: "AudioNext", keyNumber: 129 },
  AudioRewind: { keyName: "AudioRewind", keyNumber: 130 },
  AudioForward: { keyName: "AudioForward", keyNumber: 131 },
  AudioRepeat: { keyName: "AudioRepeat", keyNumber: 132 },
  AudioRandom: { keyName: "AudioRandom", keyNumber: 133 },
};

export type Key = (typeof KeyboardKeys)[keyof typeof KeyboardKeys];

type FindKey = (
  keyName: Key["keyName"] | false,
  keyNumber?: Key["keyNumber"]
) => Key;

export const findKey: FindKey = (keyName, keyNumber) =>
  Object.values(KeyboardKeys).find((k) =>
    keyName ? k.keyName === keyName : k.keyNumber === keyNumber
  ) || ({} as Key);
